//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 09:48:13 AM EDT 
//


package com.solacesystems.semp_jaxb.r7_2VMR.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for USER_MSG_SERVICE_ACCESS_LEVEL_PARAM.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="USER_MSG_SERVICE_ACCESS_LEVEL_PARAM">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="read-only"/>
 *     &lt;enumeration value="read-write"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "USER_MSG_SERVICE_ACCESS_LEVEL_PARAM")
@XmlEnum
public enum USERMSGSERVICEACCESSLEVELPARAM {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("read-only")
    READ_ONLY("read-only"),
    @XmlEnumValue("read-write")
    READ_WRITE("read-write");
    private final String value;

    USERMSGSERVICEACCESSLEVELPARAM(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static USERMSGSERVICEACCESSLEVELPARAM fromValue(String v) {
        for (USERMSGSERVICEACCESSLEVELPARAM c: USERMSGSERVICEACCESSLEVELPARAM.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
